[book]
authors = ["Ines Teles", "Lucas Reis", "Nelson"]
language = "en"
multilingual = false
src = "src"
title = "dwyl book"


[rust]
edition = "2018"

[output.html]
mathjax-support = true
site-url = "/book/"
git-repository-url = "https://github.com/dwyl/book/tree/main/src"
edit-url-template = "https://github.com/dwyl/book/edit/main/{path}"

[output.html.playground]
editable = true
line-numbers = true